### PR TITLE
feature: vite

### PR DESCRIPTION
**Pull request by marlonmarcello**
# Goal

This PR tries to accomplish three thing:

1. Modernizes and fixes the bundling process by swapping `microbundle` to `vite`
2. Improves the repo by adding a linter, formatter and a pre-commit hook to make sure files are always clean
3. Adds a development environment so we can run and test the library

⚠️ Sorry for the huge PR, most of it is deletions from the cache folders that were committed to the repo by accident when Liam was trying to fix the bundler.

## Why

The bundling process was broken and while trying to fix it by updating `microbundle` I noticed that the package even though still being quite used, is outdated when it comes to features and DX.  
`vite` being the de-facto bundler for javascript nowadays, being used on projects like vue, svelte, remix, storybook and more felt like the right choice:

1. Huge community support
2. Way more tutorials and guides online than anything else
4. Extremely simple, no need to config babel

## Notes

Just an idea, but if we all agree and like this setup, we could potentially have a template repository based on it to use for all future wtc npm packages.

### CODE REVIEW

**Comment by rvno** [comment]
nice! definitely like the idea of using vite since the setup seems simpler and ❗ no babel configs

unfortunately don't know how much I can weigh in on this pr though since I'm not familiar with this repo at all 😅

**Comment by marlonmarcello** [comment]
> unfortunately don't know how much I can weigh in on this pr though since I'm not familiar with this repo at all 😅

No worries Harvey, appreciate the quick 👀   
Mostly trying to get a feel for the update to vite, which you commented on, so thank you!

**Comment by andrewrubin** [comment]
Nice one @marlonmarcello !
Hoping I can give this a test-run in one of our apps later today!

**Comment by NicholasLancey** [comment]
Awesome @marlonmarcello! Like @rvno, I haven't had too much exposure to this repository but I'm all for simplifying/modernising the build process with Vite. Also, always nice to see this 👀 

Screenshot 2023-05-10 at 15 11 55

**Comment by marlonmarcello** [comment]
Fixed the exports and tested on a clean environment with Vite. Ready to go

**Comment by andrewrubin** [comment]
Tested using the provided local server setup — thanks for that, @marlonmarcello

There are a couple of issues I'm seeing, below. I will hopefully have a chance later this week to lend a second set of eyes here, if you like! 😃 
- sticker export is broken — I'm not getting any errors, but the output PNG is blank (maybe this is because they're GIFs?)
- `patchSticker` is throwing a number of errors in the console

This is great though, I am looking forward to re-working some of our packages with a slick new setup like this 🔥 Thanks!

**Comment by marlonmarcello** [comment]
Thanks for testing @andrewrubin !

I know that what sparked these changes was how things were being exported so I think the problem might lie in there? I will do some investigation because I remember it worked normally with the GIFs.

**Comment by marlonmarcello** [comment]
Kay, so I did some testing and it seems that the problem is the new webGL renderer. I added a background, frame and foreground and a regular png sticker and the elements that don't use the new renderer (background, foreground, image) are displayed fine on the final download.  

Going to need your help debugging this one @liamegan 
Steps to get this going locally are supa easy:
```
1. npm install
2. npm run dev
```

Make sure you are checkout to `feature/vite`

**Review by liamegan — APPROVED** [review]
This looks great, Marlon. GTG here!

**Pull request merged**
